project:
  type: website

website:
  title: "Filipe Paccetti"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/filipemendo
      - icon: twitter
        href: https://twitter.com/FilipePacc
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

